#Vehicles Attributes.
#TunerStudio by Philip Tobin
#Tue Feb 24 22:23:27 GMT 2026
converterStall=
injectorSize=60
firstGearRatio=
fourthGearRatio=
finalDriveRatio=
transmissionType=Manual
fifthGearRatio=
weight=
thirdGearRatio=
sixthGearRatio=
secondGearRatio=
engineDisplacement=1595
