#Vehicles Attributes.
#TunerStudio by Philip Tobin
#Mon Aug 10 22:02:39 BST 2026
converterStall=
injectorSize=12.1
firstGearRatio=
fourthGearRatio=
finalDriveRatio=
transmissionType=Manual
fifthGearRatio=
weight=
thirdGearRatio=
sixthGearRatio=
secondGearRatio=
engineDisplacement=1600
