#Vehicles Attributes.
#TunerStudio by Philip Tobin
#Sat May 02 12:55:09 BST 2026
converterStall=
injectorSize=34
firstGearRatio=
fourthGearRatio=
finalDriveRatio=
transmissionType=Manual
fifthGearRatio=
weight=
thirdGearRatio=
sixthGearRatio=
secondGearRatio=
engineDisplacement=1595
